### ISSUE TITLE
Program does not work as intended

### ISSUE THREAD

**Issue by parthahluwalia** [Verma92/WebDevSpring2016#1]
Server should respond with hello world when on the url route /home and not on root (/) which it is currently doing. Something like:
`app.get('/hello', function(req, res){
    res.send('hello world');
});`

And with index.html on root.

**Comment by verma-rahul** [comment]
Hi Parth,
I just wanted to Display Something at the Index.html or Root page instead of a "cannot/get" error.If you will open ' http://webdev2016-rahulverma.rhcloud.com/hello.html ' It will display as intended.I added that path in the second submission on Blackboard.And, are root and index.html not the same thing as Prof. Jose told that they are same in class?

**Comment by jannunzi** [comment]
Hi, some students did it in different ways and it's fine either way.
If the server responds "hello world" to the root or to "/hello" than it's ok
If the server responds with the index.html page to the "/" than it's ok too.
This assignment was just to validate that the openshift is working.

Thanks, Jose

Thanks,
Jose
